### ISSUE TITLE
having a sleep period

### ISSUE THREAD

**Issue by guyisra** [laserlemon/rspec-wait#13]
Is there a way to having a defined time in between retries similar to Retryable, instead of immediately retrying?

**Comment by laserlemon** [comment]
Yes, you can set `RSpec.configuration.wait_delay` globally.

Or you can use the `with_wait` block like so:

```ruby
it "works" do
  with_wait(delay: 0.5) do
    wait_for { something }.to be_done
  end
end
```

You can also pass `:wait` options to an RSpec example:

```ruby
it "works", wait: { delay: 0.5 } do
  wait_for { something }.to be_done
end
```

The default delay value is 0.1 seconds.
