### ISSUE TITLE
More detailed usage instructions?

### ISSUE THREAD

**Issue by lpender** [laserlemon/rspec-wait#25]
I had to add 

```
require "rspec/wait"
```

To my `spec_helper.rb`

May be nice to include in the README

**Comment by ericyd** [comment]
It could probably be more prominent but this is included in the https://github.com/laserlemon/rspec-wait#use-with-cucumber section

**Comment by laserlemon** [comment]
Thank you for the suggestion, this is addressed in the `v1` branch and will soon be merged to `main`. Please feel free to reopen the issue if you notice there's still room for improvement in the installation docs!
