### ISSUE TITLE
waiting on stdout?

### ISSUE THREAD

**Issue by lispercat** [laserlemon/rspec-wait#29]
sometimes it's necessary to execute the same command a few times in a row (like elasticsearch) to get to the desired state. For a simple example let's take:

```ruby
expect { system('pwd') }.to output("/home/kitchen\n").to_stdout_from_any_process
```

How do I wrap it in `wait_for` block? The naive example below doesn't work:

```ruby
expect {
  wait_for { system('pwd') }.to output("/home/kitchen\n").to_stdout_from_any_process
}.not_to raise_error
```

**Comment by asbjornu** [comment]
I'm also wondering about this.

**Comment by laserlemon** [comment]
&nbsp; &nbsp; 💭 
🤔 Hmm… thank you for the report. I'll check it out!

**Comment by laserlemon** [comment]
Ahh, I see what's going on here. RSpec::Wait currently doesn't support _block_ matchers. There is an open issue for adding support though:

- https://github.com/laserlemon/rspec-wait/pull/21

So if you have a matcher that normally takes an argument, RSpec::Wait works by taking a block instead and repeatedly evaluating that block to generate the matcher's argument. But if the matcher normally takes a block, RSpec::Wait doesn't work in those scenarios… yet.

```ruby
# This works
expect("foo").to match(/foo/)
wait_for { "foo" }.to match(/foo/)

# This doesn't
expect { bang! }.to raise_error
wait_for { bang! }.to raise_error
```

**Comment by laserlemon** [comment]
I'm going to close this issue as block matcher support has been added to the `v1` branch and a `1.0.0` version release is forthcoming. Thank you again for the report! 💛
