### ISSUE TITLE
wait_for fails when matcher does not implement supports_block_expectations?

### ISSUE THREAD

**Issue by iammer** [laserlemon/rspec-wait#34]
If you try to `wait_for { something }.to matcher` and `matcher` does not implement `supports_block_expectations?` it fails with `undefined method`.  I am running into this with Capybara, their matchers do not implement `supports_block_expectations?`.

From the documentation of `RSpec::Matchers::MatcherProtocol#supports_block_expectations?` it looks like rspec assumes false if it is not implemented.  Perhaps you should do the same?
https://rubydoc.info/github/rspec/rspec-expectations/RSpec%2FMatchers%2FMatcherProtocol:supports_block_expectations%3F

Line 17 of `handler.rb` should probably be `if matcher.try(:supports_block_expectations?)` ?

**Comment by WaKeMaTTa** [comment]
I have the same issue. My code `wait_for { page }.to have_content("Hello")` is broken.

Error:

```
NoMethodError:
  undefined method `supports_block_expectations?' for an instance of Capybara::RSpecMatchers::Matchers::HaveText
```

**Comment by laserlemon** [comment]
@iammer Thank you for the report! 💛 Are you using v1.0.0?

**Comment by laserlemon** [comment]
I just [pushed](https://github.com/laserlemon/rspec-wait/commit/3af7f317cd7c655c78743172964737df7782a2b4) a couple of tests exercising the bug and the fix to `main`. I'll release version `1.0.1` shortly! Thank you again for the report, and I'm sorry for my slow reply!

**Comment by laserlemon** [comment]
Version `1.0.1` [released](https://rubygems.org/gems/rspec-wait/versions/1.0.1)!
