### ISSUE TITLE
wait_for do not work

### ISSUE THREAD

**Issue by garmoshka-mo** [laserlemon/rspec-wait#8]
And actually whole sense of library goes away..

You can check here:

Works only with 
````
      while client.envelope.nil?
        sleep(0.1)
        p 'waiting...'
      end
````

If you remove this bock from example below, you will get:
````
expected not #<NilClass:8> => nil
         got #<NilClass:8> => nil
````

Means, this `wait_for` never understands, that value came (though it always comes with sleep block) 

````
require 'rails_helper'

describe 'Client' do
  subject(:client) { PubnubClient.new }

  context 'publishing message' do
    before do
      client.subscribe
      sleep(2)
      client.publish
    end

    it 'receives own message' do
      while client.envelope.nil?
        sleep(0.1)
        p 'waiting...'
      end
      p client.envelope
      wait_for(client.envelope).not_to be nil
      expect(client.envelope.message['attacker']).to eq 'Subzero'
      p 'ok'
    end
  end
end

class PubnubClient

  attr_reader :envelope

  def initialize
    @pubnub = Pubnub.new(
        subscribe_key: 'demo',
        publish_key: 'demo',
        :error_callback   => lambda { |msg|
          puts "Error callback says: #{msg.inspect}"
        },
        :connect_callback => lambda { |m|
          p "Someone connected #{m}"
        }
    )
  end

  def subscribe
    # first sync subscription to make sure we subscribed
    # before any messages published
    @pubnub.subscribe(:channel => 'fight_log', :http_sync => true)
    # then async listen:
    cb = lambda { |envelope| got_message envelope }
    @pubnub.subscribe(:channel => 'fight_log', :callback => cb)
  end

  def got_message(e)
    p "got message #{e.message}"
    @envelope = e
  end

  def publish
    msg = {
        attacker: 'Subzero',
        defender: 'Scorpio',
        damage: 12
    }
    @pubnub.publish(:message => msg, :channel => 'fight_log') do |m|
      p "Message sent with code #{m.status_code}"
    end
  end

end
````

**Comment by laserlemon** [comment]
Use:

```ruby
wait_for { client.envelope }.not_to be_nil
```

Note that `client.envelope` is in a block rather than being passed in as an argument to `wait_for`. That instructs RSpec::Wait to reevaluate the contents of the block for every iteration.

**Comment by garmoshka-mo** [comment]
Is from your docs:

      wait_for(ticker.tape).to eq("··-·")

Is it correct or typo here?

**Comment by laserlemon** [comment]
That's not a typo in the readme. `ticker.tape` always returns a string and over time, that string is changing in place. So for that instance, passing an argument works because the argument _itself_ is changing.

If `ticker.tape` were to change over time by returning a completely different string in memory, you'd have to use the block syntax:

```ruby
wait_for { ticker.tape }.to eq("··-·")
```

**Comment by plainlystated** [comment]
I agree that the README should be adjusted. The example of ticker.tape returning a reference to data what will be externally mutated seems pretty unrubyish and uncommon (at least in any project I've worked on). I imagine that most users of this library will find your README more misleading than helpful (as I did, and as garmoska-mo did).
