### ISSUE TITLE
Get Rspec wait with Spring - undefined method `wait_timeout='

### ISSUE THREAD

**Issue by bdougie** [laserlemon/rspec-wait#9]
I just installed rspec-wait in my work app, thanks so much for packaging this up in a gem. 

Quick question: I just noticed that when I run `spring rspec sample_spec.rb` I get the following:

```
$ spring rspec spec/features/sample_spec.rb
=> /Users/bdoug/Bloc/spec/spec_helper.rb:121:in `block in <top (required)>': undefined method `wait_timeout=' for #<RSpec::Core::Configuration:0x007fc936575330> (NoMethodError)
```

Do you have any familiarity with how to get this `wait_timeout` method included in spring. 

I am doing my part in figuring it out but wanted to throw the question out there in case you had familiarity with spring in your own app, If not no worries, I will eventually figure it out.

*currently running Rails 4.1.2

**Comment by bdougie** [comment]
Wow, rookie mistake: I never ran `spring stop`. If you don't mind, I might open a pr to add a note on the readme about spring. If it's not need feel free to decline.

**Comment by mhenrixon** [comment]
I don't see why that entry is needed after all. It has absolutely nothing to do with `rspec-wait` but is rather a common problem when using spring. We could have that README entry for every single gem in the whole of ruby gems. 

My suggestion is to close this issue and the pull request without merging those changes or every gem in the universe will soon have knowledge in their readme about spring.
